### ISSUE TITLE
All frequencies can receive different frequencies

### ISSUE THREAD

**Issue by deltaflyer4747** [esnya/UdonRadioCommunications#20] opened 2022-04-11 23:19 UTC
If i set my receiver to freq. A and other person transmits on freq B, i am still able to hear other person and he can hear me when i transmit.

**Comment by esnya** [comment] 2023-02-17 15:48
This issue is closed as it is not able to reproduce over a long time. An update for U#1 will be released soon.

**Closed by esnya** 2023-02-17 15:48 UTC
